#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

# Requirements:

#    Accepts 4 parameters
#        The path to the file to be transferred
#        The IP of the server we want to transfer the file to
#        The username scp connects with
#        The path to the SSH private key that scp uses
#    Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#        if less than 3 parameters passed
#    scp must transfer the file to the user home directory ~/
#    Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# parameters

path_to_file=$1
ip=$2
user_name=$3
path_to_ssh_key=$4

# turning off strict host key chechking when using scp

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$user_name@$ip:~/"

# checking whether the file transfered successfuly or not

if [ $? -eq 0 ]
then
	echo "Successfuly Transfered."
else
	echo "Not successfuly transfered"
fi
