#!/usr/bin/env bash
# A bash script Configure Nginx server to have a custom 404 page that contains
# the string Ceci n'est pas une page

sudo apt-get update -y
sudo apt-get install -y nginx

# redirecting to a page
echo "Hello World!" | sudo tee /var/www/html/index.html

string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Henok-Haile permanent;"

sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

# customing a 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default

# Testing configuration for syntax errors
sudo nginx -t

# reload nginx after implmenting changes
sudo service nginx reload
sudo service nginx restart
