#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# (on web-01 and web-02)

# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server nginx
# is running on

# Updating packes
sudo apt-get update
sudo apt-get install -y nginx

# allowing firewall through port 80
sudo ufw allow 'Nginx HTTP' 

# creating /var/www/html if it doesn't exist
sudo mkdir -p /var/www/html

# allowing permission to create files easily
sudo chmod -R 755 /var/www

# creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirecting a page(/redirect_me) and adding a header to display a hostname
string="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/github.com\/Henok-Haile permanent;"

sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-available/default

# customing a 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-available/default

# Test for syntax errors
sudo nginx -t

# Restarting nginx
sudo service nginx restart
