#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# (on web-01 and web-02)

# Updating packes
sudo apt-get update
sudo apt-get install -y nginx

# creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirecting a page
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Henok-Haile permanent;"

sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

# customing a 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default

# add_http_header
sudo sed -i "/server _name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t

# Restarting nginx
sudo service nginx restart

# reload nginx after implmenting changes
sudo service nginx reload
sudo service nginx restart
