#!/usr/bin/env bash
# updating package and installing haproxy on lb-01
sudo apt-get -y update
sudo apt-get -y install haproxy

# configuring config.cfg file
server_config=\
"
frontend henok-fronted
        bind *:80
        mode http
        default_backend henok-backend

backend henok-backend
        balance roundrobin
        server 49828-web-01 100.25.47.158:80 check
        server 49828-web-02 35.153.193.110:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# restart haproxy
sudo service haproxy restart
