#!/usr/bin/env bash
# Install and configure HAproxy

# Update Packages
apt-get -y update
apt-get -y upgrade

# Add Haproxy PPA
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
app-get -y update

# Install Haproxy
apt-get -y install haproxy=2.0.\*

# Configure Haproxy
config="\
frontend balancer
    bind *:80
    mode http
    default_backend servers

backend servers
    balance roundrobin
    server 49828-web-01 100.25.164.254:80 check
    server 49828-web-02 34.203.201.252:80 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
