#!/usr/bin/env bash
#a Bash script that displays Best School 10 times using while loop
# but display "bud luck" and "good luck" for 4th and 8th iteration respectively.

i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
