#!/usr/bin/env bash
# configures ufw so that it blocks all incoming traffic
# except TCP ports 22(SSH), 443(HTTPS SSL), and 80(HTTP)

sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/Tcp
sudo ufw allow 443/Tcp
sudo ufw allow 80/Tcp
sudo ufw status verbose
sudo ufw enable
sudo ufw status verbose
