#!/usr/bin/env bash
# configures ufw so that it blocks all incoming traffic
# except TCP ports 22(ssh), 443(https ssl), and 80(http)

sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw status verbose
sudo ufw enable
sudo ufw status verbose
